version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: workspace2
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ~/.ssh/id_rsa|\.\w+:/root/.ssh/
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - drone_utm
  backend:
    image: nginx:alpine
    container_name: backend2
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/sites-enabled/:/etc/nginx/conf.d/
      - ./docker/nginx/snippets/:/etc/nginx/snippets/
      - ./docker/logs/nginx:/var/log/nginx
      - /etc/hosts:/etc/hosts
    ports:
      - ${WEB_PORT}:80
    networks:
      drone_utm:
        aliases:
          - api.carle.test
  database:
    image: mysql:5.7
    container_name: database2
    volumes:
      - ./docker/database/data:/var/lib/mysql/
      - ./docker/database/carle_demo.sql:/var/lib/carle_demo.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    networks:
      - drone_utm
networks:
  drone_utm:
    driver: bridge
volumes:
  dbdata:
    driver: local
    